---
- hosts: ios
  gather_facts: no



  tasks:

  - name: OBTAIN VARS
    include_vars: ./group_vars/ios.yml
  
#  - name: "GET CONFIG"
#    ios_command:
#      commands:
#        - "show running-config full | include ntp server"
#    register: get_config

#  - debug: var=get_config.stdout_lines

#  - name: RUN 'Set NTP'
#    with_items: "{{ ntp_servers }}"
#    ios_config:
#      lines:
#          - "{{ item }}"
#    register: set_ntp

#  - name: RUN 'Remove NTP'
#    when: "(get_config.stdout_lines[0] != '') and (item not in ntp_servers)"
#    with_items: "{{ get_config.stdout_lines[0] }}"
#    register: remove_ntp
#    ios_config:
#      lines:
#        - "no {{ item }}"

#  - name: servicenow_network_tickets
#    when: set_ntp.changed or remove_ntp.changed
#    import_role:
#      name: servicenow_network_tickets

  - name: Generate documentation
    template:
      src: ./templates/global_configs.j2
      dest: ./documentation/global_configs.md
    delegate_to: localhost
    run_once: true
    check_mode: no
#    tags:
#      - documentation
#      - config
